In [ ]:
import pandas as pd
import numpy as np


In [ ]:
x =np.array([2 ,3, 4, 5, 6, 7])
y = np.array([1, 5, 3, 6, 7, 8])


In [ ]:
# data = np.array([[2,1],[3,5],[4,3],[5,6],[6,7],[7,8]])

In [ ]:
x_mean=x.mean()
y_mean=y.mean()
# Y_mean=Y.mean()


In [ ]:
data=np.array([x,y])

In [ ]:
cov_mat = np.cov(data,bias=True)
cov_mat

array([[2.91666667, 3.66666667],
       [3.66666667, 5.66666667]])

In [ ]:
eigenvalues,eigenvectors=np.linalg.eig(cov_mat)

In [ ]:
eigenvalues

array([0.37566495, 8.20766838])

In [ ]:
eigenvectors

array([[-0.82192562, -0.56959484],
       [ 0.56959484, -0.82192562]])

In [ ]:

# Index the eigenvalues in descending order
idx = eigenvalues.argsort()[::-1]
print(idx)


# Sort the eigenvalues in descending order
eigenvalues = eigenvalues[idx]
print(eigenvalues)

# sort the corresponding eigenvectors accordingly
eigenvectors = eigenvectors[:,idx]
print(eigenvectors)

[1 0]
[8.20766838 0.37566495]
[[-0.56959484 -0.82192562]
 [-0.82192562  0.56959484]]


In [ ]:
explained_var = np.cumsum(eigenvalues) / np.sum(eigenvalues)
explained_var

array([0.95623321, 1.        ])

In [ ]:

n_components = np.argmax(explained_var >= 0.50) + 1
n_components =2

In [ ]:

# PCA component or unit matrix
u = eigenvectors[:,:n_components]
pca_component = pd.DataFrame(u,
                             index =  [x,y],
                             columns = ['PC1','PC2']
                            )

ValueError: Shape of passed values is (2, 2), indices imply (6, 2)

In [ ]:
ev = eigenvalues[1]